version: '2'

services:
  web:
    build: ./apache-php
    ports:
      - 80:80
    volumes:
      - ./code:/var/www/html/
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.100.105"
      PHP_IDE_CONFIG: "serverName=Docker-Apache-PHP"
#    networks:
#      static-network:
#        ipv4_address: 172.20.128.1

  db:
    build: ./mysql
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
#    networks:
#      static-network:
#        ipv4_address: 172.20.128.2

#networks:
#  static-network:
#    ipam:
#      config:
#        - subnet: 172.20.0.0/16
#          ip_range: 172.28.5.0/24